CREATE TABLE IF NOT EXISTS so_users (
  id VARCHAR PRIMARY KEY,
  username VARCHAR NOT NULL,
  email VARCHAR NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS so_sessions (
  id SERIAL PRIMARY KEY,
  user_id VARCHAR REFERENCES so_users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS so_requests (
  id SERIAL PRIMARY KEY,
  session_id INTEGER REFERENCES so_sessions(id),
  request_data JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);